export let country = [{ key: "AF", value: "Afghanistan" },
    { key: "AX", value: "Aland Islands" },
    { key: "AL", value: "Albania" },
    { key: "DZ", value: "Algeria" },
    { key: "AD", value: "Andorra" },
    { key: "AO", value: "Angola" },
    { key: "AI", value: "Anguilla" },
    { key: "AG", value: "Antigua and Barbuda" },
    { key: "AR", value: "Argentina" },
    { key: "AM", value: "Armenia" },
    { key: "AW", value: "Aruba" },
    { key: "AU", value: "Australia" },
    { key: "AT", value: "Austria" },
    { key: "AZ", value: "Azerbaijan" },
    { key: "BS", value: "Bahamas" },
    { key: "BH", value: "Bahrain" },
    { key: "BD", value: "Bangladesh" },
    { key: "BB", value: "Barbados" },
    { key: "BY", value: "Belarus" },
    { key: "BE", value: "Belgium" },
    { key: "BZ", value: "Belize" },
    { key: "BJ", value: "Benin" },
    { key: "BM", value: "Bermuda" },
    { key: "BT", value: "Bhutan" },
    { key: "BO", value: "Bolivia" },
    { key: "BQ", value: "Bonaire, int Eustatius and Saba" },
    { key: "BA", value: "Bosnia and Herzegovina" },
    { key: "BW", value: "Botswana" },
    { key: "BR", value: "Brazil" },
    { key: "BN", value: "Brunei Darussalam" },
    { key: "BG", value: "Bulgaria" },
    { key: "BF", value: "Burkina Faso" },
    { key: "KH", value: "Cambodia" },
    { key: "CM", value: "Cameroon" },
    { key: "CA", value: "Canada" },
    { key: "CV", value: "Cape Verde" },
    { key: "KY", value: "Cayman Islands" },
    { key: "CF", value: "Central African Republic" },
    { key: "CL", value: "Chile" },
    { key: "CN", value: "China" },
    { key: "CC", value: "Cocos (Keeling) Islands" },
    { key: "CO", value: "Colombia" },
    { key: "CR", value: "Costa Rica" },
    { key: "CI", value: "C&#244;te d'Ivoire" },
    { key: "HR", value: "Croatia" },
    { key: "CW", value: "Cura&#231;ao" },
    { key: "CY", value: "Cyprus" },
    { key: "CZ", value: "Czech Republic" },
    { key: "DK", value: "Denmark" },
    { key: "DJ", value: "Djibouti" },
    { key: "DM", value: "Dominica" },
    { key: "DO", value: "Dominican Republic" },
    { key: "EC", value: "Ecuador" },
    { key: "EG", value: "Egypt" },
    { key: "SV", value: "El Salvador" },
    { key: "GQ", value: "Equatorial Guinea" },
    { key: "EE", value: "Estonia" },
    { key: "ET", value: "Ethiopia" },
    { key: "FO", value: "Faroe Islands" },
    { key: "FJ", value: "Fiji" },
    { key: "FI", value: "Finland" },
    { key: "FR", value: "France" },
    { key: "GF", value: "French Guiana" },
    { key: "PF", value: "French Polynesia" },
    { key: "GM", value: "Gambia" },
    { key: "GB", value: "Great Britain" },
    { key: "GE", value: "Georgia" },
    { key: "DE", value: "Germany" },
    { key: "GH", value: "Ghana" },
    { key: "GI", value: "Gibraltar" },
    { key: "GR", value: "Greece" },
    { key: "GL", value: "Greenland" },
    { key: "GD", value: "Grenada" },
    { key: "GP", value: "Guadeloupe" },
    { key: "GU", value: "Guam" },
    { key: "GT", value: "Guatemala" },
    { key: "GG", value: "Guernsey" },
    { key: "GN", value: "Guinea" },
    { key: "GY", value: "Guyana" },
    { key: "HT", value: "Haiti" },
    { key: "HN", value: "Honduras" },
    { key: "HK", value: "Hong Kong" },
    { key: "HU", value: "Hungary" },
    { key: "IS", value: "Iceland" },
    { key: "IN", value: "India" },
    { key: "ID", value: "Indonesia" },
    { key: "IR", value: "Iran" },
    { key: "IQ", value: "Iraq" },
    { key: "IE", value: "Ireland" },
    { key: "IM", value: "Isle of Man" },
    { key: "IL", value: "Israel" },
    { key: "IT", value: "Italy" },
    { key: "JM", value: "Jamaica" },
    { key: "JP", value: "Japan" },
    { key: "JE", value: "Jersey" },
    { key: "JO", value: "Jordan" },
    { key: "KZ", value: "Kazakhstan" },
    { key: "KE", value: "Kenya" },
    { key: "KR", value: "Korea - South" },
    { key: "KW", value: "Kuwait" },
    { key: "KG", value: "Kyrgyzstan" },
    { key: "LA", value: "Laos" },
    { key: "LV", value: "Latvia" },
    { key: "LB", value: "Lebanon" },
    { key: "LR", value: "Liberia" },
    { key: "LY", value: "Libya" },
    { key: "LI", value: "Liechtenstein" },
    { key: "LT", value: "Lithuania" },
    { key: "LU", value: "Luxembourg" },
    { key: "MO", value: "Macao" },
    { key: "MK", value: "Macedonia" },
    { key: "MG", value: "Madagascar" },
    { key: "MW", value: "Malawi" },
    { key: "MY", value: "Malaysia" },
    { key: "MV", value: "Maldives" },
    { key: "ML", value: "Mali" },
    { key: "MT", value: "Malta" },
    { key: "MH", value: "Marshall Islands" },
    { key: "MQ", value: "Martinique" },
    { key: "MU", value: "Mauritius" },
    { key: "MX", value: "Mexico" },
    { key: "MD", value: "Moldova" },
    { key: "MC", value: "Monaco" },
    { key: "MN", value: "Mongolia" },
    { key: "ME", value: "Montenegro" },
    { key: "MS", value: "Montserrat" },
    { key: "MA", value: "Morocco" },
    { key: "MZ", value: "Mozambique" },
    { key: "MM", value: "Myanmar" },
    { key: "NR", value: "Nauru" },
    { key: "NP", value: "Nepal" },
    { key: "NL", value: "Netherlands" },
    { key: "NC", value: "New Caledonia" },
    { key: "NZ", value: "New Zealand" },
    { key: "NI", value: "Nicaragua" },
    { key: "NE", value: "Niger" },
    { key: "NG", value: "Nigeria" },
    { key: "MP", value: "Northern Mariana Islands" },
    { key: "NO", value: "Norway" },
    { key: "OM", value: "Oman" },
    { key: "PK", value: "Pakistan" },
    { key: "PS", value: "Palestinian Territory" },
    { key: "PA", value: "Panama" },
    { key: "PY", value: "Paraguay" },
    { key: "PE", value: "Peru" },
    { key: "PH", value: "Philippines" },
    { key: "PL", value: "Poland" },
    { key: "PT", value: "Portugal" },
    { key: "PR", value: "Puerto Rico" },
    { key: "QA", value: "Qatar" },
    { key: "RE", value: "Reunion" },
    { key: "RO", value: "Romania" },
    { key: "RU", value: "Russian Federation" },
    { key: "RW", value: "Rwanda" },
    { key: "KN", value: "Saint Kitts and Nevis" },
    { key: "LC", value: "Saint Lucia" },
    { key: "MF", value: "Saint Martin" },
    { key: "VC", value: "Saint Vincent and the Grenadines" },
    { key: "WS", value: "Samoa" },
    { key: "SA", value: "Saudi Arabia" },
    { key: "SN", value: "Senegal" },
    { key: "RS", value: "Serbia" },
    { key: "SC", value: "Seychelles" },
    { key: "SL", value: "Sierra Leone" },
    { key: "SG", value: "Singapore" },
    { key: "SX", value: "Sint Maarten (Dutch part)" },
    { key: "SK", value: "Slovakia" },
    { key: "SI", value: "Slovenia" },
    { key: "SO", value: "Somalia" },
    { key: "ZA", value: "South Africa" },
    { key: "ES", value: "Spain" },
    { key: "LK", value: "Sri Lanka" },
    { key: "SD", value: "Sudan" },
    { key: "SR", value: "Suriname" },
    { key: "SZ", value: "Swaziland" },
    { key: "SE", value: "Sweden" },
    { key: "CH", value: "Switzerland" },
    { key: "SY", value: "Syria" },
    { key: "TW", value: "Taiwan" },
    { key: "TJ", value: "Tajikistan" },
    { key: "TZ", value: "Tanzania, nited Republic of" },
    { key: "TH", value: "Thailand" },
    { key: "TL", value: "Timor-Leste" },
    { key: "TT", value: "Trinidad and Tobago" },
    { key: "TN", value: "Tunisia" },
    { key: "TR", value: "Turkey" },
    { key: "TM", value: "Turkmenistan" },
    { key: "TC", value: "Turks and Caicos Islands" },
    { key: "UG", value: "Uganda" },
    { key: "UA", value: "Ukraine" },
    { key: "AE", value: "United Arab Emirates" },
    { key: "UK", value: "United Kingdom" },
    { key: "US", value: "United States" },
    { key: "UY", value: "Uruguay" },
    { key: "UZ", value: "Uzbekistan" },
    { key: "VU", value: "Vanuatu" },
    { key: "VE", value: "Venezuela, olivarian Republic of" },
    { key: "VN", value: "Vietnam" },
    { key: "VG", value: "Virgin Islands, ritish" },
    { key: "VY", value: "Virgin Islands, .S." },
    { key: "YE", value: "Yemen" },
    { key: "ZM", value: "Zambia" },
    { key: "ZW", value: "Zimbabwe" }];